# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-10 11:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180610_1129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcategory',
            options={'verbose_name': 'category', 'verbose_name_plural': 'post categories'},
        ),
    ]
