# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-10 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180610_1129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcategory',
            options={'verbose_name': 'category', 'verbose_name_plural': 'Post Categories'},
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='image',
            field=models.ImageField(upload_to='blog/category/%Y/%F/%l/%d/'),
        ),
    ]
