# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-11 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20180611_0633'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorygroup',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categorygroup',
            name='name',
            field=models.CharField(choices=[('men', 'Men'), ('ladies', 'Ladies'), ('kids', 'Kids')], max_length=20, null=True),
        ),
    ]
