# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-11 07:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20180611_0703'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colours',
            options={'verbose_name': 'colour', 'verbose_name_plural': 'colours'},
        ),
        migrations.AddField(
            model_name='productcategory',
            name='cat_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.CategoryGroup'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productcategory',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product/category/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productcategory',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='colours',
            name='color_code',
            field=models.CharField(blank=True, help_text='visit https://www.w3schools.com/colors/colors_picker.asp', max_length=20, null=True),
        ),
    ]
