# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-10 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shophome', '0002_auto_20180610_0756'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetInspired',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('image', models.ImageField(upload_to='homepage/get-inspired/%Y/%m/%d/')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
            ],
            options={
                'verbose_name': 'Get Inspired Image',
                'verbose_name_plural': 'Get Inspired Images',
            },
        ),
    ]
