# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-10 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shophome', '0003_getinspired'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.CharField(max_length=2)),
                ('limit', models.CharField(max_length=5)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
