# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-12 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shophome', '0004_topoffer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('image_large', models.ImageField(blank=True, null=True, upload_to='homepage/logo/%Y/%m/%d/')),
                ('image_small', models.ImageField(blank=True, null=True, upload_to='homepage/logo/%Y/%m/%d/')),
                ('create', models.DateTimeField(auto_now_add=True, null=True)),
                ('update', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
