# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-12 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shophome', '0007_auto_20180612_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('postcode', models.CharField(blank=True, max_length=12, null=True)),
                ('division', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('call_center_info', models.TextField(blank=True, null=True)),
                ('call_center_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('electronic_support', models.TextField(blank=True, null=True)),
                ('electronic_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('electronic_ticket_link', models.URLField(blank=True, max_length=300, null=True)),
                ('electronic_ticket', models.CharField(blank=True, max_length=250, null=True)),
                ('map_snippet', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Contact Us',
                'verbose_name_plural': 'Contact Us Page',
            },
        ),
    ]
