# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-12 18:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shophome', '0008_contactuspage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactuspage',
            name='create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactuspage',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
