# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-13 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shophome', '0010_aboutus'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='image_one',
            field=models.ImageField(blank=True, null=True, upload_to='about/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='image_three',
            field=models.ImageField(blank=True, null=True, upload_to='about/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='image_two',
            field=models.ImageField(blank=True, null=True, upload_to='about/%Y/%m/%d/'),
        ),
    ]
